<aside class="span3 well">
    <ul>
        <li><a href="<?php echo $this->url('phly-paste') ?>">Create new paste</a></li>
        <li><a href="<?php echo $this->url('zfcuser') ?>">Login/Logout</a> (login to remove CAPTCHAs)</li>
        <li><a href="<?php echo $this->url('phly-paste/list') ?>">List pastes</a></li>
        <li><a href="<?php echo $this->url('phly-paste/help') ?>">Help</a></li>
    </ul>
</aside>
