#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
( unset GIT_DIR ; export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer" ; cd $OPENSHIFT_REPO_DIR ; /usr/local/zend/bin/php composer.phar install )
